# ============================================================
# Project Specification: see .agents/AGENTS.md
# ============================================================

# supported: 'python','R'

project.layout = 'python'
