##
# customization: project source consts
#
# ---(project)---
CUST_S_PROJECT_NAME='dve-sample-r'
# ---(package)---
CUST_S_PACKAGE_NAME='dvesimpler'
# ---(source repository)---
CUST_S_REPO_PATH='ub-dems-public/ds-labs'
CUST_S_REPO_HOST='https://gitlab.com/'
# ---(image registry)---
CUST_S_REGS_PATH='ubdems'
CUST_S_REGS_HOST='docker.io'
# ---(environment versions)---
CUST_S_IMAGE_ANCHOR='rocker/geospatial:4.5.2'
CUST_S_VERS_BASE='(>= 4.4.0)'
CUST_S_VERS_ROXY='7.3.2'
# ---(data import links)---
CUST_S_DATA_LINK='dve-ds'
CUST_S_DATA_DEMO='1'
# ---(renv support options)---
CUST_S_RENV_OPTS='enable,auto'
# ---(project description)---
CUST_S_INFO_AUTH_NAME='datalab'
CUST_S_INFO_AUTH_SURNAME='DEMS'
CUST_S_INFO_AUTH_EMAIL='datalab@unimib.it'
CUST_S_INFO_DESC='TODO:description'
CUST_S_INFO_TITLE='TODO:title'
# ---(image labels)---
CUST_S_INFO_USER_EMAIL='dsuser.dems@gmail.com'
CUST_S_INFO_AUTHORS="${CUST_S_INFO_AUTH_SURNAME}/${CUST_S_INFO_AUTH_NAME} <${CUST_S_INFO_USER_EMAIL}>"
CUST_S_INFO_FROM='2026-03-16'
CUST_S_INFO_OWNER='ab21010'
CUST_S_INFO_CDC='ds-101'
CUST_S_INFO_TAGS='none'

