##
# customization: project target consts
#
# ---(project)---
CUST_T_PROJECT_NAME='us-proto-r'
# ---(package)---
CUST_T_R_PACKAGE_NAME='USprotoR'
CUST_T_PY_PACKAGE_NAME='us_proto_r'
# ---(source repository)---
CUST_T_REPO_PATH='ub-dems/cs-labs/user-dsuser'
CUST_T_CICD_PATH="${CUST_T_REPO_PATH}"
CUST_T_REPO_HOST='https://gitlab.com/'
# ---(image registry)---
CUST_T_REGS_PATH='ubdems'
CUST_T_REGS_HOST='docker.io'
# ---(environment versions)---
CUST_T_IMAGE_ANCHOR='rocker/geospatial:4.6.1'
CUST_T_VERS_BASE='(>= 4.6.0)'
CUST_T_VERS_ROXY='8.1.0'
# ---(data import links)---
CUST_T_DATA_LINK='dat-ds'
CUST_T_DATA_DEMO='1'
# ---(renv support options)---
CUST_T_RENV_OPTS='enable,auto'
# ---(project description)---
CUST_T_INFO_AUTH_NAME='_GivenName_'
CUST_T_INFO_AUTH_SURNAME='_SurName_'
CUST_T_INFO_AUTH_EMAIL='nil@campus.unimib.it'
CUST_T_INFO_TITLE='TODO(title): TITLE OF THE WORK'
CUST_T_INFO_DESC='TODO(desc): SHORT DESCRIPTION OF THE WORK'
# ---(image labels)---
CUST_T_INFO_OWNER="$USER"
CUST_T_INFO_USER_EMAIL="${CUST_T_INFO_AUTH_EMAIL}"
CUST_T_INFO_AUTHORS="${CUST_T_INFO_AUTH_SURNAME}/${CUST_T_INFO_AUTH_NAME} <${CUST_T_INFO_USER_EMAIL}>"
CUST_T_INFO_FROM="$(date +%Y-%m-%d)"
CUST_T_INFO_CDC='es-620'
CUST_T_INFO_TAGS="ds.user=${CUST_T_INFO_OWNER},ds.task=${CUST_T_INFO_OWNER}.1"
