##
# customization: project target consts
#
# ---(project)---
CUST_T_PROJECT_NAME='us-proto-r'
# ---(package)---
CUST_T_PACKAGE_NAME='USprotoR'
# ---(source repository)---
CUST_T_REPO_PATH='ub-dems/cs-labs/user-dsuser'
CUST_T_REPO_HOST='https://gitlab.com/'
# ---(image registry)---
CUST_T_REGS_PATH='_ubdems_'
CUST_T_REGS_HOST='_docker.io_'
# ---(environment versions)---
CUST_T_IMAGE_ANCHOR='_rocker/tidyverse:latest_'
CUST_T_VERS_BASE='_(>= 3.6.0)_'
CUST_T_VERS_ROXY='_7.2.0_'
# ---(data import links)---
CUST_T_DATA_LINK='_dve-ds_'
# ---(renv support options)---
CUST_T_RENV_OPTS='enable,auto'
# ---(project description)---
CUST_T_INFO_AUTH_NAME='_datalab_'
CUST_T_INFO_AUTH_SURNAME='_DEMS_'
CUST_T_INFO_AUTH_EMAIL='_datalab@unimib.it_'
CUST_T_INFO_DESC='_TODO:description_'
CUST_T_INFO_TITLE='_TODO:title_'
# ---(image labels)---
CUST_T_INFO_USER_EMAIL='_dsuser.dems@gmail.com'
CUST_T_INFO_AUTHORS="${CUST_T_INFO_AUTH_SURNAME}/${CUST_T_INFO_AUTH_NAME} <${CUST_T_INFO_USER_EMAIL}>"
CUST_T_INFO_FROM='_2022-08-02_'
CUST_T_INFO_OWNER='_ab21010_'
CUST_T_INFO_CDC='_ds-101_'
CUST_T_INFO_TAGS='_none_'
