##
# customization: project target consts
#
# ---(project)---
CUST_T_PROJECT_NAME='us-proto-r'
# ---(package)---
CUST_T_PACKAGE_NAME='USprotoR'
# ---(source repository)---
CUST_T_REPO_PATH='ub-dems/cs-labs/user-dsuser'
CUST_T_REPO_HOST='https://gitlab.com/'
# ---(image registry)---
CUST_T_REGS_PATH='ubdems'
CUST_T_REGS_HOST='docker.io'
# ---(environment versions)---
CUST_T_IMAGE_ANCHOR='rocker/geospatial:4.4.3'
CUST_T_VERS_BASE='(>= 4.0.0)'
CUST_T_VERS_ROXY='7.3.2'
# ---(data import links)---
CUST_T_DATA_LINK='dve-ds'
CUST_T_DATA_DEMO='1'
# ---(renv support options)---
CUST_T_RENV_OPTS='enable,auto'
# ---(project description)---
CUST_T_INFO_AUTH_NAME='datalab'
CUST_T_INFO_AUTH_SURNAME='DEMS'
CUST_T_INFO_AUTH_EMAIL='datalab@unimib.it'
CUST_T_INFO_DESC='TODO:description'
CUST_T_INFO_TITLE='TODO:title'
# ---(image labels)---
CUST_T_INFO_USER_EMAIL='dsuser.dems@gmail.com'
CUST_T_INFO_AUTHORS="${CUST_T_INFO_AUTH_SURNAME}/${CUST_T_INFO_AUTH_NAME} <${CUST_T_INFO_USER_EMAIL}>"
CUST_T_INFO_FROM='2022-08-02'
CUST_T_INFO_OWNER='ab21010'
CUST_T_INFO_CDC='ds-101'
CUST_T_INFO_TAGS='none'
