// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_dvesimpler_RCPPEXPORTS_H_GEN_
#define RCPP_dvesimpler_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

namespace dvesimpler {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("dvesimpler", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("dvesimpler", "_dvesimpler_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in dvesimpler");
            }
        }
    }

    inline NumericVector dmy_gsl_beta(NumericVector a, NumericVector b) {
        typedef SEXP(*Ptr_dmy_gsl_beta)(SEXP,SEXP);
        static Ptr_dmy_gsl_beta p_dmy_gsl_beta = NULL;
        if (p_dmy_gsl_beta == NULL) {
            validateSignature("NumericVector(*dmy_gsl_beta)(NumericVector,NumericVector)");
            p_dmy_gsl_beta = (Ptr_dmy_gsl_beta)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_gsl_beta");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_gsl_beta(Shield<SEXP>(Rcpp::wrap(a)), Shield<SEXP>(Rcpp::wrap(b)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

    inline Rcpp::NumericVector dmy_custom_mean(Rcpp::NumericVector data) {
        typedef SEXP(*Ptr_dmy_custom_mean)(SEXP);
        static Ptr_dmy_custom_mean p_dmy_custom_mean = NULL;
        if (p_dmy_custom_mean == NULL) {
            validateSignature("Rcpp::NumericVector(*dmy_custom_mean)(Rcpp::NumericVector)");
            p_dmy_custom_mean = (Ptr_dmy_custom_mean)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_custom_mean");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_custom_mean(Shield<SEXP>(Rcpp::wrap(data)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::NumericVector >(rcpp_result_gen);
    }

    inline void dmy_print_mean(Rcpp::NumericVector data) {
        typedef SEXP(*Ptr_dmy_print_mean)(SEXP);
        static Ptr_dmy_print_mean p_dmy_print_mean = NULL;
        if (p_dmy_print_mean == NULL) {
            validateSignature("void(*dmy_print_mean)(Rcpp::NumericVector)");
            p_dmy_print_mean = (Ptr_dmy_print_mean)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_print_mean");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_print_mean(Shield<SEXP>(Rcpp::wrap(data)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

    inline List dmy_summary_stats(const NumericVector& data, double confidence_level, bool na_rm) {
        typedef SEXP(*Ptr_dmy_summary_stats)(SEXP,SEXP,SEXP);
        static Ptr_dmy_summary_stats p_dmy_summary_stats = NULL;
        if (p_dmy_summary_stats == NULL) {
            validateSignature("List(*dmy_summary_stats)(const NumericVector&,double,bool)");
            p_dmy_summary_stats = (Ptr_dmy_summary_stats)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_summary_stats");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_summary_stats(Shield<SEXP>(Rcpp::wrap(data)), Shield<SEXP>(Rcpp::wrap(confidence_level)), Shield<SEXP>(Rcpp::wrap(na_rm)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

    inline DataFrame dmy_dplyr_grouped_sum(DataFrame df, String group_col, String value_col) {
        typedef SEXP(*Ptr_dmy_dplyr_grouped_sum)(SEXP,SEXP,SEXP);
        static Ptr_dmy_dplyr_grouped_sum p_dmy_dplyr_grouped_sum = NULL;
        if (p_dmy_dplyr_grouped_sum == NULL) {
            validateSignature("DataFrame(*dmy_dplyr_grouped_sum)(DataFrame,String,String)");
            p_dmy_dplyr_grouped_sum = (Ptr_dmy_dplyr_grouped_sum)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_dplyr_grouped_sum");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_dplyr_grouped_sum(Shield<SEXP>(Rcpp::wrap(df)), Shield<SEXP>(Rcpp::wrap(group_col)), Shield<SEXP>(Rcpp::wrap(value_col)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<DataFrame >(rcpp_result_gen);
    }

    inline DataFrame dmy_group_op(const DataFrame& data, const std::string& group_col, const std::string& value_col, const std::string& operation) {
        typedef SEXP(*Ptr_dmy_group_op)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_dmy_group_op p_dmy_group_op = NULL;
        if (p_dmy_group_op == NULL) {
            validateSignature("DataFrame(*dmy_group_op)(const DataFrame&,const std::string&,const std::string&,const std::string&)");
            p_dmy_group_op = (Ptr_dmy_group_op)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_group_op");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_group_op(Shield<SEXP>(Rcpp::wrap(data)), Shield<SEXP>(Rcpp::wrap(group_col)), Shield<SEXP>(Rcpp::wrap(value_col)), Shield<SEXP>(Rcpp::wrap(operation)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<DataFrame >(rcpp_result_gen);
    }

    inline arma::mat dmy_matrix_multiplication_arma(const arma::mat& A, const arma::mat& B) {
        typedef SEXP(*Ptr_dmy_matrix_multiplication_arma)(SEXP,SEXP);
        static Ptr_dmy_matrix_multiplication_arma p_dmy_matrix_multiplication_arma = NULL;
        if (p_dmy_matrix_multiplication_arma == NULL) {
            validateSignature("arma::mat(*dmy_matrix_multiplication_arma)(const arma::mat&,const arma::mat&)");
            p_dmy_matrix_multiplication_arma = (Ptr_dmy_matrix_multiplication_arma)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_matrix_multiplication_arma");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_matrix_multiplication_arma(Shield<SEXP>(Rcpp::wrap(A)), Shield<SEXP>(Rcpp::wrap(B)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline Rcpp::List dmy_eigen_decomposition_arma(const arma::mat& X) {
        typedef SEXP(*Ptr_dmy_eigen_decomposition_arma)(SEXP);
        static Ptr_dmy_eigen_decomposition_arma p_dmy_eigen_decomposition_arma = NULL;
        if (p_dmy_eigen_decomposition_arma == NULL) {
            validateSignature("Rcpp::List(*dmy_eigen_decomposition_arma)(const arma::mat&)");
            p_dmy_eigen_decomposition_arma = (Ptr_dmy_eigen_decomposition_arma)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_eigen_decomposition_arma");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_eigen_decomposition_arma(Shield<SEXP>(Rcpp::wrap(X)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline Eigen::MatrixXd dmy_gram_matrix_eigen(const Eigen::Map<Eigen::MatrixXd>& A) {
        typedef SEXP(*Ptr_dmy_gram_matrix_eigen)(SEXP);
        static Ptr_dmy_gram_matrix_eigen p_dmy_gram_matrix_eigen = NULL;
        if (p_dmy_gram_matrix_eigen == NULL) {
            validateSignature("Eigen::MatrixXd(*dmy_gram_matrix_eigen)(const Eigen::Map<Eigen::MatrixXd>&)");
            p_dmy_gram_matrix_eigen = (Ptr_dmy_gram_matrix_eigen)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_gram_matrix_eigen");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_gram_matrix_eigen(Shield<SEXP>(Rcpp::wrap(A)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Eigen::MatrixXd >(rcpp_result_gen);
    }

    inline List dmy_linear_regression_eigen(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::VectorXd>& y) {
        typedef SEXP(*Ptr_dmy_linear_regression_eigen)(SEXP,SEXP);
        static Ptr_dmy_linear_regression_eigen p_dmy_linear_regression_eigen = NULL;
        if (p_dmy_linear_regression_eigen == NULL) {
            validateSignature("List(*dmy_linear_regression_eigen)(const Eigen::Map<Eigen::MatrixXd>&,const Eigen::Map<Eigen::VectorXd>&)");
            p_dmy_linear_regression_eigen = (Ptr_dmy_linear_regression_eigen)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_linear_regression_eigen");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_linear_regression_eigen(Shield<SEXP>(Rcpp::wrap(X)), Shield<SEXP>(Rcpp::wrap(y)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

    inline Rcpp::NumericVector dmy_df_custom_summarize(Rcpp::DataFrame df, Rcpp::String column) {
        typedef SEXP(*Ptr_dmy_df_custom_summarize)(SEXP,SEXP);
        static Ptr_dmy_df_custom_summarize p_dmy_df_custom_summarize = NULL;
        if (p_dmy_df_custom_summarize == NULL) {
            validateSignature("Rcpp::NumericVector(*dmy_df_custom_summarize)(Rcpp::DataFrame,Rcpp::String)");
            p_dmy_df_custom_summarize = (Ptr_dmy_df_custom_summarize)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_df_custom_summarize");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_df_custom_summarize(Shield<SEXP>(Rcpp::wrap(df)), Shield<SEXP>(Rcpp::wrap(column)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::NumericVector >(rcpp_result_gen);
    }

    inline Rcpp::NumericVector dmy_df_rolling_average(Rcpp::NumericVector x, int n) {
        typedef SEXP(*Ptr_dmy_df_rolling_average)(SEXP,SEXP);
        static Ptr_dmy_df_rolling_average p_dmy_df_rolling_average = NULL;
        if (p_dmy_df_rolling_average == NULL) {
            validateSignature("Rcpp::NumericVector(*dmy_df_rolling_average)(Rcpp::NumericVector,int)");
            p_dmy_df_rolling_average = (Ptr_dmy_df_rolling_average)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_df_rolling_average");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_df_rolling_average(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(n)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::NumericVector >(rcpp_result_gen);
    }

    inline Rcpp::DataFrame dmy_df_process_data(Rcpp::DataFrame df) {
        typedef SEXP(*Ptr_dmy_df_process_data)(SEXP);
        static Ptr_dmy_df_process_data p_dmy_df_process_data = NULL;
        if (p_dmy_df_process_data == NULL) {
            validateSignature("Rcpp::DataFrame(*dmy_df_process_data)(Rcpp::DataFrame)");
            p_dmy_df_process_data = (Ptr_dmy_df_process_data)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_df_process_data");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_df_process_data(Shield<SEXP>(Rcpp::wrap(df)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::DataFrame >(rcpp_result_gen);
    }

    inline Rcpp::RObject dmy_df_call_dplyr_mutate() {
        typedef SEXP(*Ptr_dmy_df_call_dplyr_mutate)();
        static Ptr_dmy_df_call_dplyr_mutate p_dmy_df_call_dplyr_mutate = NULL;
        if (p_dmy_df_call_dplyr_mutate == NULL) {
            validateSignature("Rcpp::RObject(*dmy_df_call_dplyr_mutate)()");
            p_dmy_df_call_dplyr_mutate = (Ptr_dmy_df_call_dplyr_mutate)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_df_call_dplyr_mutate");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_df_call_dplyr_mutate();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::RObject >(rcpp_result_gen);
    }

}

#endif // RCPP_dvesimpler_RCPPEXPORTS_H_GEN_
