// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_dvesimpler_RCPPEXPORTS_H_GEN_
#define RCPP_dvesimpler_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

namespace dvesimpler {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("dvesimpler", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("dvesimpler", "_dvesimpler_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in dvesimpler");
            }
        }
    }

    inline NumericVector dmy_gsl_beta(NumericVector a, NumericVector b) {
        typedef SEXP(*Ptr_dmy_gsl_beta)(SEXP,SEXP);
        static Ptr_dmy_gsl_beta p_dmy_gsl_beta = NULL;
        if (p_dmy_gsl_beta == NULL) {
            validateSignature("NumericVector(*dmy_gsl_beta)(NumericVector,NumericVector)");
            p_dmy_gsl_beta = (Ptr_dmy_gsl_beta)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_gsl_beta");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_gsl_beta(Shield<SEXP>(Rcpp::wrap(a)), Shield<SEXP>(Rcpp::wrap(b)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

    inline Rcpp::NumericVector dmy_custom_mean(Rcpp::NumericVector data) {
        typedef SEXP(*Ptr_dmy_custom_mean)(SEXP);
        static Ptr_dmy_custom_mean p_dmy_custom_mean = NULL;
        if (p_dmy_custom_mean == NULL) {
            validateSignature("Rcpp::NumericVector(*dmy_custom_mean)(Rcpp::NumericVector)");
            p_dmy_custom_mean = (Ptr_dmy_custom_mean)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_custom_mean");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_custom_mean(Shield<SEXP>(Rcpp::wrap(data)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::NumericVector >(rcpp_result_gen);
    }

    inline void dmy_print_mean(Rcpp::NumericVector data) {
        typedef SEXP(*Ptr_dmy_print_mean)(SEXP);
        static Ptr_dmy_print_mean p_dmy_print_mean = NULL;
        if (p_dmy_print_mean == NULL) {
            validateSignature("void(*dmy_print_mean)(Rcpp::NumericVector)");
            p_dmy_print_mean = (Ptr_dmy_print_mean)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_print_mean");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_print_mean(Shield<SEXP>(Rcpp::wrap(data)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
    }

    inline List dmy_summary_stats(const NumericVector& data, double confidence_level, bool na_rm) {
        typedef SEXP(*Ptr_dmy_summary_stats)(SEXP,SEXP,SEXP);
        static Ptr_dmy_summary_stats p_dmy_summary_stats = NULL;
        if (p_dmy_summary_stats == NULL) {
            validateSignature("List(*dmy_summary_stats)(const NumericVector&,double,bool)");
            p_dmy_summary_stats = (Ptr_dmy_summary_stats)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_summary_stats");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_summary_stats(Shield<SEXP>(Rcpp::wrap(data)), Shield<SEXP>(Rcpp::wrap(confidence_level)), Shield<SEXP>(Rcpp::wrap(na_rm)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

    inline DataFrame dmy_dplyr_grouped_sum(DataFrame df, String group_col, String value_col) {
        typedef SEXP(*Ptr_dmy_dplyr_grouped_sum)(SEXP,SEXP,SEXP);
        static Ptr_dmy_dplyr_grouped_sum p_dmy_dplyr_grouped_sum = NULL;
        if (p_dmy_dplyr_grouped_sum == NULL) {
            validateSignature("DataFrame(*dmy_dplyr_grouped_sum)(DataFrame,String,String)");
            p_dmy_dplyr_grouped_sum = (Ptr_dmy_dplyr_grouped_sum)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_dplyr_grouped_sum");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_dplyr_grouped_sum(Shield<SEXP>(Rcpp::wrap(df)), Shield<SEXP>(Rcpp::wrap(group_col)), Shield<SEXP>(Rcpp::wrap(value_col)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<DataFrame >(rcpp_result_gen);
    }

    inline DataFrame dmy_group_op(const DataFrame& data, const std::string& group_col, const std::string& value_col, const std::string& operation) {
        typedef SEXP(*Ptr_dmy_group_op)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_dmy_group_op p_dmy_group_op = NULL;
        if (p_dmy_group_op == NULL) {
            validateSignature("DataFrame(*dmy_group_op)(const DataFrame&,const std::string&,const std::string&,const std::string&)");
            p_dmy_group_op = (Ptr_dmy_group_op)R_GetCCallable("dvesimpler", "_dvesimpler_dmy_group_op");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_dmy_group_op(Shield<SEXP>(Rcpp::wrap(data)), Shield<SEXP>(Rcpp::wrap(group_col)), Shield<SEXP>(Rcpp::wrap(value_col)), Shield<SEXP>(Rcpp::wrap(operation)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<DataFrame >(rcpp_result_gen);
    }

}

#endif // RCPP_dvesimpler_RCPPEXPORTS_H_GEN_
