##
#  /etc/build.conf: build-time environment configuration
#

# ---(buid debug)---------------------------

Y_DEBUG=1

# ---(python support)---------------------------

Y_PY_PYTHON_VERSION=3.11

Y_PY_PYENV_INSTALL=1
Y_PY_PYENV_PYTHON=1

Y_PY_POETRY_INSTALL=1

Y_PY_RETICULATE_INSTALL=1
Y_PY_RETICULATE_CONFIG=1

Y_PY_JUPYTER_INSTALL=1
Y_PY_JUPYTER_CONFIG=1




