##
#  /etc/cuda.conf: cuda environment configuration
#

# ---(build debug)---------------------------

Y_DEBUG=0
#Y_DEBUG_ENV=0  # Dockerfile ARG: Y_DEBUG_ENV


# //////////////////////////////////////////////////
# /// CUDA
# //////////////////////////////////////////////////

# ---(globals)---------------------------

Y_NV_ANY_SUPPORT=1

Y_NV_CUDA_SETUP=mamba
#Y_NV_CUDA_SETUP=12.560
#Y_NV_CUDA_SETUP=11.470
#Y_NV_CUDA_SETUP=none


Y_NV_CONDA_ENV_NAME=cuda-base
Y_NV_CONDA_ENV_FILE=conda-cuda-env.yaml


# ---(mamba)---------------------------

Y_NV_MAMBA_SUPPORT=0 # disabled, CUDA libs from PyPi (torch)

#Y_NV_MAMBA_SUPPORT=1
Y_NV_MAMBA_INSTALL=1
Y_NV_MAMBA_ENVIRON=1
Y_NV_MAMBA_ENABLE=1
Y_NV_MAMBA_CHECK=1


# ---(utils)---------------------------

Y_NV_UTILS_SUPPORT=1
Y_NV_UTILS_TOOLS=1
Y_NV_UTILS_CHECK=1


# ---(apt-cuda)---------------------------

# Y_NV_CUDA_REPO=1
# Y_NV_CUDA_MAMBA=1
# Y_NV_CUDA_SUPPORT=1
# Y_NV_CUDA_TOOLKIT=0
# Y_NV_CUDA_CUDNN=0
# Y_NV_CUDA_NVINFER=0   #TensorRT
# Y_NV_CUDA_BLAS=0
# Y_NV_CUDA_NVTOP=1
# #Y_NV_CUDA_DRIVER=0
# #Y_NV_CUDA_COMPAT=0
# #Y_NV_CUDA_LINKER=0
# #Y_NV_CUDA_COMPILER=1
# #Y_NV_CUDA_LIBRARIES=1
# #Y_NV_CUDA_TOOLS=1
# Y_NV_CUDA_CHECK=0

