##
#  /etc/project.conf: project meta info
#


# //////////////////////////////////////////////////
# /// PROJECT META INFO
# //////////////////////////////////////////////////

# ---(language)---------------------------

X_PRJ_KIND=R       # R project
#X_PRJ_KIND=P       # python project


# ---(Build commands)---------------------------

X_BLD_R=0
X_BLD_R_MAN_KNITR=0

X_BLD_P=0
X_BLD_P_MAN_SPHINIX=0


case "$X_PRJ_KIND" in
     R)
     X_BLD_P=1
     X_BLD_R=1
     X_BLD_R_MAN_KNITR=1
     ;;
     P)
     X_BLD_P=1
     X_BLD_R=1
     X_BLD_P_MAN_SPHINIX=1
     ;;
esac     


# ---(XWindow)---------------------------

X_X=1     # enable X support

# ---(XDG)---------------------------

X_XDG_MOUNT=1  # mount XDG user folders


