##
#  /etc/runtime.conf: runtime-time environment configuration
#

# ---(runtime debug)---------------------------

X_DEF_DEBUG=0
X_DEF_DEBUG_ENV=0

# //////////////////////////////////////////////////
# /// ARGS
# //////////////////////////////////////////////////

# ---(language)---------------------------

X_DEF_KIND=auto       # check *.Rproj


# ---(startup)---------------------------

X_DEF_RUN_R_COMMAND=rstudio
X_DEF_RUN_P_COMMAND=sh

