// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dvesimpler.h"
#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmy_pf_log_set_level
void dmy_pf_log_set_level(int level);
RcppExport SEXP _dvesimpler_dmy_pf_log_set_level(SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    dmy_pf_log_set_level(level);
    return R_NilValue;
END_RCPP
}
// dmy_pf_log_get_level
int dmy_pf_log_get_level();
RcppExport SEXP _dvesimpler_dmy_pf_log_get_level() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dmy_pf_log_get_level());
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_log_reset
void dmy_pf_log_reset();
RcppExport SEXP _dvesimpler_dmy_pf_log_reset() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    dmy_pf_log_reset();
    return R_NilValue;
END_RCPP
}
// dmy_pf_log_out
void dmy_pf_log_out(const std::string& file, int line, const std::string& message);
RcppExport SEXP _dvesimpler_dmy_pf_log_out(SEXP fileSEXP, SEXP lineSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file(fileSEXP);
    Rcpp::traits::input_parameter< int >::type line(lineSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type message(messageSEXP);
    dmy_pf_log_out(file, line, message);
    return R_NilValue;
END_RCPP
}
// dmy_pf_log_trace
void dmy_pf_log_trace(const std::string& file, int line, const std::string& message);
RcppExport SEXP _dvesimpler_dmy_pf_log_trace(SEXP fileSEXP, SEXP lineSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type file(fileSEXP);
    Rcpp::traits::input_parameter< int >::type line(lineSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type message(messageSEXP);
    dmy_pf_log_trace(file, line, message);
    return R_NilValue;
END_RCPP
}
// dmy_pf_sum_c_style
double dmy_pf_sum_c_style(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_c_style(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_c_style(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_sum_cpp_range
double dmy_pf_sum_cpp_range(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_cpp_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_cpp_range(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_sum_stl_iter
double dmy_pf_sum_stl_iter(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_stl_iter(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_stl_iter(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_sum_omp_parallel
double dmy_pf_sum_omp_parallel(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_omp_parallel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_omp_parallel(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_sum_omp_simd
double dmy_pf_sum_omp_simd(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_omp_simd(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_omp_simd(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_sum_armadillo
double dmy_pf_sum_armadillo(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_armadillo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_armadillo(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_sum_r_base
double dmy_pf_sum_r_base(const NumericVector& x);
RcppExport SEXP _dvesimpler_dmy_pf_sum_r_base(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_sum_r_base(x));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_outer_c_style
NumericMatrix dmy_pf_outer_c_style(const NumericVector& x, const NumericVector& y);
RcppExport SEXP _dvesimpler_dmy_pf_outer_c_style(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_outer_c_style(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_outer_cpp_iter
NumericMatrix dmy_pf_outer_cpp_iter(const NumericVector& x, const NumericVector& y);
RcppExport SEXP _dvesimpler_dmy_pf_outer_cpp_iter(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_outer_cpp_iter(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_outer_omp_collapse
NumericMatrix dmy_pf_outer_omp_collapse(const NumericVector& x, const NumericVector& y);
RcppExport SEXP _dvesimpler_dmy_pf_outer_omp_collapse(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_outer_omp_collapse(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_outer_omp_simd
NumericMatrix dmy_pf_outer_omp_simd(const NumericVector& x, const NumericVector& y);
RcppExport SEXP _dvesimpler_dmy_pf_outer_omp_simd(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_outer_omp_simd(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_outer_armadillo
NumericMatrix dmy_pf_outer_armadillo(const NumericVector& x, const NumericVector& y);
RcppExport SEXP _dvesimpler_dmy_pf_outer_armadillo(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_outer_armadillo(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dmy_pf_outer_r_base
NumericMatrix dmy_pf_outer_r_base(const NumericVector& x, const NumericVector& y);
RcppExport SEXP _dvesimpler_dmy_pf_outer_r_base(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_pf_outer_r_base(x, y));
    return rcpp_result_gen;
END_RCPP
}
// package_info
Rcpp::List package_info();
RcppExport SEXP _dvesimpler_package_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(package_info());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dvesimpler_dmy_pf_log_set_level", (DL_FUNC) &_dvesimpler_dmy_pf_log_set_level, 1},
    {"_dvesimpler_dmy_pf_log_get_level", (DL_FUNC) &_dvesimpler_dmy_pf_log_get_level, 0},
    {"_dvesimpler_dmy_pf_log_reset", (DL_FUNC) &_dvesimpler_dmy_pf_log_reset, 0},
    {"_dvesimpler_dmy_pf_log_out", (DL_FUNC) &_dvesimpler_dmy_pf_log_out, 3},
    {"_dvesimpler_dmy_pf_log_trace", (DL_FUNC) &_dvesimpler_dmy_pf_log_trace, 3},
    {"_dvesimpler_dmy_pf_sum_c_style", (DL_FUNC) &_dvesimpler_dmy_pf_sum_c_style, 1},
    {"_dvesimpler_dmy_pf_sum_cpp_range", (DL_FUNC) &_dvesimpler_dmy_pf_sum_cpp_range, 1},
    {"_dvesimpler_dmy_pf_sum_stl_iter", (DL_FUNC) &_dvesimpler_dmy_pf_sum_stl_iter, 1},
    {"_dvesimpler_dmy_pf_sum_omp_parallel", (DL_FUNC) &_dvesimpler_dmy_pf_sum_omp_parallel, 1},
    {"_dvesimpler_dmy_pf_sum_omp_simd", (DL_FUNC) &_dvesimpler_dmy_pf_sum_omp_simd, 1},
    {"_dvesimpler_dmy_pf_sum_armadillo", (DL_FUNC) &_dvesimpler_dmy_pf_sum_armadillo, 1},
    {"_dvesimpler_dmy_pf_sum_r_base", (DL_FUNC) &_dvesimpler_dmy_pf_sum_r_base, 1},
    {"_dvesimpler_dmy_pf_outer_c_style", (DL_FUNC) &_dvesimpler_dmy_pf_outer_c_style, 2},
    {"_dvesimpler_dmy_pf_outer_cpp_iter", (DL_FUNC) &_dvesimpler_dmy_pf_outer_cpp_iter, 2},
    {"_dvesimpler_dmy_pf_outer_omp_collapse", (DL_FUNC) &_dvesimpler_dmy_pf_outer_omp_collapse, 2},
    {"_dvesimpler_dmy_pf_outer_omp_simd", (DL_FUNC) &_dvesimpler_dmy_pf_outer_omp_simd, 2},
    {"_dvesimpler_dmy_pf_outer_armadillo", (DL_FUNC) &_dvesimpler_dmy_pf_outer_armadillo, 2},
    {"_dvesimpler_dmy_pf_outer_r_base", (DL_FUNC) &_dvesimpler_dmy_pf_outer_r_base, 2},
    {"_dvesimpler_package_info", (DL_FUNC) &_dvesimpler_package_info, 0},
    {NULL, NULL, 0}
};

void package_init(DllInfo *dll);
RcppExport void R_init_dvesimpler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    package_init(dll);
}
