// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dummy_mean_v0
double dummy_mean_v0(NumericVector xs);
RcppExport SEXP _dvesimpler_dummy_mean_v0(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(dummy_mean_v0(xs));
    return rcpp_result_gen;
END_RCPP
}
// dummy_mean_v1
double dummy_mean_v1(NumericVector xs);
RcppExport SEXP _dvesimpler_dummy_mean_v1(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(dummy_mean_v1(xs));
    return rcpp_result_gen;
END_RCPP
}
// dummy_mean_v2
double dummy_mean_v2(NumericVector xs);
RcppExport SEXP _dvesimpler_dummy_mean_v2(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(dummy_mean_v2(xs));
    return rcpp_result_gen;
END_RCPP
}
// dummy_mean_v3
double dummy_mean_v3(NumericVector xs);
RcppExport SEXP _dvesimpler_dummy_mean_v3(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(dummy_mean_v3(xs));
    return rcpp_result_gen;
END_RCPP
}
// dummy_mean
double dummy_mean(NumericVector xs);
RcppExport SEXP _dvesimpler_dummy_mean(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(dummy_mean(xs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dvesimpler_dummy_mean_v0", (DL_FUNC) &_dvesimpler_dummy_mean_v0, 1},
    {"_dvesimpler_dummy_mean_v1", (DL_FUNC) &_dvesimpler_dummy_mean_v1, 1},
    {"_dvesimpler_dummy_mean_v2", (DL_FUNC) &_dvesimpler_dummy_mean_v2, 1},
    {"_dvesimpler_dummy_mean_v3", (DL_FUNC) &_dvesimpler_dummy_mean_v3, 1},
    {"_dvesimpler_dummy_mean", (DL_FUNC) &_dvesimpler_dummy_mean, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dvesimpler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
