// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dvesimpler.h"
#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmy_gsl_beta
NumericVector dmy_gsl_beta(NumericVector a, NumericVector b);
static SEXP _dvesimpler_dmy_gsl_beta_try(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_gsl_beta(a, b));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _dvesimpler_dmy_gsl_beta(SEXP aSEXP, SEXP bSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_dvesimpler_dmy_gsl_beta_try(aSEXP, bSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dmy_mean
Rcpp::NumericVector dmy_mean(NumericVector xs);
RcppExport SEXP _dvesimpler_dmy_mean(SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_mean(xs));
    return rcpp_result_gen;
END_RCPP
}
// dmy_custom_mean
Rcpp::NumericVector dmy_custom_mean(Rcpp::NumericVector data);
static SEXP _dvesimpler_dmy_custom_mean_try(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_custom_mean(data));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _dvesimpler_dmy_custom_mean(SEXP dataSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_dvesimpler_dmy_custom_mean_try(dataSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dmy_print_mean
void dmy_print_mean(Rcpp::NumericVector data);
static SEXP _dvesimpler_dmy_print_mean_try(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    dmy_print_mean(data);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _dvesimpler_dmy_print_mean(SEXP dataSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_dvesimpler_dmy_print_mean_try(dataSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dmy_summary_stats
List dmy_summary_stats(const NumericVector& data, double confidence_level, bool na_rm);
static SEXP _dvesimpler_dmy_summary_stats_try(SEXP dataSEXP, SEXP confidence_levelSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type confidence_level(confidence_levelSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_summary_stats(data, confidence_level, na_rm));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _dvesimpler_dmy_summary_stats(SEXP dataSEXP, SEXP confidence_levelSEXP, SEXP na_rmSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_dvesimpler_dmy_summary_stats_try(dataSEXP, confidence_levelSEXP, na_rmSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dmy_dplyr_grouped_sum
DataFrame dmy_dplyr_grouped_sum(DataFrame df, String group_col, String value_col);
static SEXP _dvesimpler_dmy_dplyr_grouped_sum_try(SEXP dfSEXP, SEXP group_colSEXP, SEXP value_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< String >::type group_col(group_colSEXP);
    Rcpp::traits::input_parameter< String >::type value_col(value_colSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_dplyr_grouped_sum(df, group_col, value_col));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _dvesimpler_dmy_dplyr_grouped_sum(SEXP dfSEXP, SEXP group_colSEXP, SEXP value_colSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_dvesimpler_dmy_dplyr_grouped_sum_try(dfSEXP, group_colSEXP, value_colSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// dmy_group_op
DataFrame dmy_group_op(const DataFrame& data, const std::string& group_col, const std::string& value_col, const std::string& operation);
static SEXP _dvesimpler_dmy_group_op_try(SEXP dataSEXP, SEXP group_colSEXP, SEXP value_colSEXP, SEXP operationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type group_col(group_colSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type value_col(value_colSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type operation(operationSEXP);
    rcpp_result_gen = Rcpp::wrap(dmy_group_op(data, group_col, value_col, operation));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _dvesimpler_dmy_group_op(SEXP dataSEXP, SEXP group_colSEXP, SEXP value_colSEXP, SEXP operationSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_dvesimpler_dmy_group_op_try(dataSEXP, group_colSEXP, value_colSEXP, operationSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// package_info
Rcpp::List package_info();
RcppExport SEXP _dvesimpler_package_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(package_info());
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _dvesimpler_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericVector(*dmy_gsl_beta)(NumericVector,NumericVector)");
        signatures.insert("Rcpp::NumericVector(*dmy_custom_mean)(Rcpp::NumericVector)");
        signatures.insert("void(*dmy_print_mean)(Rcpp::NumericVector)");
        signatures.insert("List(*dmy_summary_stats)(const NumericVector&,double,bool)");
        signatures.insert("DataFrame(*dmy_dplyr_grouped_sum)(DataFrame,String,String)");
        signatures.insert("DataFrame(*dmy_group_op)(const DataFrame&,const std::string&,const std::string&,const std::string&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _dvesimpler_RcppExport_registerCCallable() { 
    R_RegisterCCallable("dvesimpler", "_dvesimpler_dmy_gsl_beta", (DL_FUNC)_dvesimpler_dmy_gsl_beta_try);
    R_RegisterCCallable("dvesimpler", "_dvesimpler_dmy_custom_mean", (DL_FUNC)_dvesimpler_dmy_custom_mean_try);
    R_RegisterCCallable("dvesimpler", "_dvesimpler_dmy_print_mean", (DL_FUNC)_dvesimpler_dmy_print_mean_try);
    R_RegisterCCallable("dvesimpler", "_dvesimpler_dmy_summary_stats", (DL_FUNC)_dvesimpler_dmy_summary_stats_try);
    R_RegisterCCallable("dvesimpler", "_dvesimpler_dmy_dplyr_grouped_sum", (DL_FUNC)_dvesimpler_dmy_dplyr_grouped_sum_try);
    R_RegisterCCallable("dvesimpler", "_dvesimpler_dmy_group_op", (DL_FUNC)_dvesimpler_dmy_group_op_try);
    R_RegisterCCallable("dvesimpler", "_dvesimpler_RcppExport_validate", (DL_FUNC)_dvesimpler_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_dvesimpler_dmy_gsl_beta", (DL_FUNC) &_dvesimpler_dmy_gsl_beta, 2},
    {"_dvesimpler_dmy_mean", (DL_FUNC) &_dvesimpler_dmy_mean, 1},
    {"_dvesimpler_dmy_custom_mean", (DL_FUNC) &_dvesimpler_dmy_custom_mean, 1},
    {"_dvesimpler_dmy_print_mean", (DL_FUNC) &_dvesimpler_dmy_print_mean, 1},
    {"_dvesimpler_dmy_summary_stats", (DL_FUNC) &_dvesimpler_dmy_summary_stats, 3},
    {"_dvesimpler_dmy_dplyr_grouped_sum", (DL_FUNC) &_dvesimpler_dmy_dplyr_grouped_sum, 3},
    {"_dvesimpler_dmy_group_op", (DL_FUNC) &_dvesimpler_dmy_group_op, 4},
    {"_dvesimpler_package_info", (DL_FUNC) &_dvesimpler_package_info, 0},
    {"_dvesimpler_RcppExport_registerCCallable", (DL_FUNC) &_dvesimpler_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

void package_init(DllInfo *dll);
RcppExport void R_init_dvesimpler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    package_init(dll);
}
