# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate vectorized Beta function
#' @description This function calculates Beta function with GSL library.
#' @param a A NumericVector of Beta first argument (a)
#' @param b A NumericVector of Beta second argument (b)
#' @return A NumericVector of Beta(a,b)
#' @examples
#' \dontrun{
#' a <- c(1/2, 1, 3/2, 2)
#' b <- c(1/2, 1, 3/2, 2)
#' beta <- dmy_gsl_beta(a,b)
#' print(beta)
#' }
#' @export
dmy_gsl_beta <- function(a, b) {
    .Call(`_dvesimpler_dmy_gsl_beta`, a, b)
}

dmy_mean <- function(xs) {
    .Call(`_dvesimpler_dmy_mean`, xs)
}

#' Calculate Aritmetic Mean 
#'
#' Compute mean directly without C or R library funcions
#' with exported package function
#' See: dummy_mean.cpp
#'
#' @param data A numeric vector
#'
#' @return Arithmetic mean of data
#'
#' @examples
#' \dontrun{
#' data <- rnorm(100)
#' m <- dmy_custom_mean(data)
#' }
#'
#' @export
dmy_custom_mean <- function(data) {
    .Call(`_dvesimpler_dmy_custom_mean`, data)
}

#' Print Aritmetic Mean 
#'
#' Print mean calling internal package custom_mean
#' calls inline namespace version from Rcpp::compileAttributes()
#' See: inst/include/*.h
#'
#' @param data A numeric vector
#'
#' @return Arithmetic mean of data
#'
#' @examples
#' \dontrun{
#' data <- rnorm(100)
#' m <- dmy_custom_mean(data)
#' }
#'
#' @export
dmy_print_mean <- function(data) {
    invisible(.Call(`_dvesimpler_dmy_print_mean`, data))
}

#' Calculate Robust Summary Statistics
#'
#' Computes comprehensive summary statistics for a numeric vector with
#' robust error handling and missing value treatment.
#'
#' @param data A numeric vector
#' @param confidence_level Confidence level for intervals (default: 0.95)
#' @param na_rm Remove NA values (default: TRUE)
#'
#' @return A named list with summary statistics
#'
#' @examples
#' \dontrun{
#' data <- rnorm(100)
#' stats <- dmy_summary_stats(data)
#' }
#'
#' @export
dmy_summary_stats <- function(data, confidence_level, na_rm) {
    .Call(`_dvesimpler_dmy_summary_stats`, data, confidence_level, na_rm)
}

#' Calculate a Summry Dataframme as a sum, by group colun
#'
#' Aggregate by sum value column bt group column
#' 
#' @param df An input dataframme
#' @param group_col keys column name
#' @param value_col values column name
#'
#' @return A two column dataframe with keys and valuue
#'
#' @examples
#' \dontrun{
#' data <- rnorm(100)
#' stats <- dmy_summary_stats(data)
#' }
#'
#' @export
dmy_dplyr_grouped_sum <- function(df, group_col, value_col) {
    .Call(`_dvesimpler_dmy_dplyr_grouped_sum`, df, group_col, value_col)
}

#' Efficient Group Operations
#'
#' Performs group-wise operations on data frames efficiently in C++.
#'
#' @param data Data frame
#' @param group_col Name of the grouping column
#' @param value_col Name of the value column
#' @param operation Operation to perform ("mean", "sum", "count", "sd")
#'
#' @return Data frame with group results
#'
#' @export
dmy_group_op <- function(data, group_col, value_col, operation) {
    .Call(`_dvesimpler_dmy_group_op`, data, group_col, value_col, operation)
}

package_info <- function() {
    .Call(`_dvesimpler_package_info`)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_dvesimpler_RcppExport_registerCCallable`)
})
