# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Set logging verbosity level
#' @param level Integer verbosity level (0=info, 3=trace)
#' @export
dmy_pf_log_set_level <- function(level) {
    invisible(.Call(`_dvesimpler_dmy_pf_log_set_level`, level))
}

#' Get current logging level
#' @return Current verbosity level
#' @export
dmy_pf_log_get_level <- function() {
    .Call(`_dvesimpler_dmy_pf_log_get_level`)
}

#' Reset trace location tracking
#' @export
dmy_pf_log_reset <- function() {
    invisible(.Call(`_dvesimpler_dmy_pf_log_reset`))
}

#' Output log message if verbosity >= 0
#' @param file Source file name
#' @param line Line number  
#' @param message Log message
#' @export
dmy_pf_log_out <- function(file, line, message) {
    invisible(.Call(`_dvesimpler_dmy_pf_log_out`, file, line, message))
}

#' Output trace message if verbosity >= 3 (once per location)
#' @param file Source file name
#' @param line Line number
#' @param message Trace message  
#' @export
dmy_pf_log_trace <- function(file, line, message) {
    invisible(.Call(`_dvesimpler_dmy_pf_log_trace`, file, line, message))
}

#' Sum using C-style for loop with manual indexing
#' @param x Numeric vector to sum
#' @return Sum of vector elements
#' @examples
#' \dontrun{
#' x <- rnorm(1000)
#' result <- dmy_pf_sum_c_style(x)
#' }
#' @export
dmy_pf_sum_c_style <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_c_style`, x)
}

#' Sum using C++11 range-based for loop
#' @param x Numeric vector to sum  
#' @return Sum of vector elements
#' @examples
#' \dontrun{
#' x <- rnorm(1000)
#' result <- dmy_pf_sum_cpp_range(x)
#' }
#' @export
dmy_pf_sum_cpp_range <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_cpp_range`, x)
}

#' Sum using STL iterators
#' @param x Numeric vector to sum
#' @return Sum of vector elements  
#' @examples
#' \dontrun{
#' x <- rnorm(1000)
#' result <- dmy_pf_sum_stl_iter(x)
#' }
#' @export
dmy_pf_sum_stl_iter <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_stl_iter`, x)
}

#' Sum using OpenMP parallel reduction
#' @param x Numeric vector to sum
#' @return Sum of vector elements
#' @examples  
#' \dontrun{
#' x <- rnorm(10000)
#' result <- dmy_pf_sum_omp_parallel(x)
#' }
#' @export
dmy_pf_sum_omp_parallel <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_omp_parallel`, x)
}

#' Sum using OpenMP parallel for with SIMD vectorization
#' @param x Numeric vector to sum
#' @return Sum of vector elements
#' @examples
#' \dontrun{
#' x <- rnorm(10000)  
#' result <- dmy_pf_sum_omp_simd(x)
#' }
#' @export
dmy_pf_sum_omp_simd <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_omp_simd`, x)
}

#' Sum using RcppArmadillo
#' @param x Numeric vector to sum
#' @return Sum of vector elements
#' @examples
#' \dontrun{
#' x <- rnorm(1000)
#' result <- dmy_pf_sum_armadillo(x)  
#' }
#' @export
dmy_pf_sum_armadillo <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_armadillo`, x)
}

#' Sum using R base::sum function called from C++
#' @param x Numeric vector to sum
#' @return Sum of vector elements
#' @examples
#' \dontrun{
#' x <- rnorm(1000)
#' result <- dmy_pf_sum_r_base(x)
#' }
#' @export  
dmy_pf_sum_r_base <- function(x) {
    .Call(`_dvesimpler_dmy_pf_sum_r_base`, x)
}

#' Outer product using C-style nested loops
#' @param x First input vector
#' @param y Second input vector  
#' @return Matrix representing outer product
#' @examples
#' \dontrun{
#' x <- rnorm(100)
#' y <- rnorm(100)
#' result <- dmy_pf_outer_c_style(x, y)
#' }
#' @export
dmy_pf_outer_c_style <- function(x, y) {
    .Call(`_dvesimpler_dmy_pf_outer_c_style`, x, y)
}

#' Outer product using C++ STL iterators
#' @param x First input vector
#' @param y Second input vector
#' @return Matrix representing outer product  
#' @examples
#' \dontrun{
#' x <- rnorm(100)
#' y <- rnorm(100)
#' result <- dmy_pf_outer_cpp_iter(x, y)
#' }
#' @export
dmy_pf_outer_cpp_iter <- function(x, y) {
    .Call(`_dvesimpler_dmy_pf_outer_cpp_iter`, x, y)
}

#' Outer product using OpenMP collapsed parallel loops
#' @param x First input vector
#' @param y Second input vector
#' @return Matrix representing outer product
#' @examples
#' \dontrun{
#' x <- rnorm(500)
#' y <- rnorm(500)  
#' result <- dmy_pf_outer_omp_collapse(x, y)
#' }
#' @export
dmy_pf_outer_omp_collapse <- function(x, y) {
    .Call(`_dvesimpler_dmy_pf_outer_omp_collapse`, x, y)
}

#' Outer product using OpenMP parallel outer loop with SIMD inner loop
#' @param x First input vector  
#' @param y Second input vector
#' @return Matrix representing outer product
#' @examples
#' \dontrun{
#' x <- rnorm(500)
#' y <- rnorm(500)
#' result <- dmy_pf_outer_omp_simd(x, y)
#' }
#' @export
dmy_pf_outer_omp_simd <- function(x, y) {
    .Call(`_dvesimpler_dmy_pf_outer_omp_simd`, x, y)
}

#' Outer product using RcppArmadillo
#' @param x First input vector
#' @param y Second input vector
#' @return Matrix representing outer product
#' @examples
#' \dontrun{
#' x <- rnorm(100)
#' y <- rnorm(100)
#' result <- dmy_pf_outer_armadillo(x, y)
#' }
#' @export
dmy_pf_outer_armadillo <- function(x, y) {
    .Call(`_dvesimpler_dmy_pf_outer_armadillo`, x, y)
}

#' Outer product using R base::outer function called from C++
#' @param x First input vector
#' @param y Second input vector  
#' @return Matrix representing outer product
#' @examples
#' \dontrun{
#' x <- rnorm(100)
#' y <- rnorm(100)
#' result <- dmy_pf_outer_r_base(x, y)
#' }
#' @export
dmy_pf_outer_r_base <- function(x, y) {
    .Call(`_dvesimpler_dmy_pf_outer_r_base`, x, y)
}

package_info <- function() {
    .Call(`_dvesimpler_package_info`)
}

